name: C/C++ CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: clang-format
      uses: jayllyz/clang-format-action@v1
      with:
        check: true
        style: file
        extensions: cxx,hpp

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy
    - name: Run clang-tidy
      run: |
        find . -name '*.cxx' -or -name '*.hpp' | xargs clang-tidy -p build
    - name: Echo
      run: |
        echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate
      run: cmake -S . -B bin
    - name: Build
      run: |
          cd bin
          make -j $(nproc)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: bin
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: Test
        run: |
          cd bin
          ./SafeCastTest
