name: C/C++ CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- name: Install clang-format
      #run: sudo apt-get install -y clang-format
    - name: Debug
      run: |
        clang-format --version
        clang-tidy --version
        pwd
    - name: Clang-format
      run: find . -name '*.cxx' -or -name '*.hpp' | xargs clang-format --dry-run -Werror
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy
    - name: Generate
      run: cmake -S . -B bin -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - name: Build
      run: |
          cd bin
          make -j $(nproc)
    - name: Clang-tidy
      run: |
        find . -name '*.cxx' -or -name '*.hpp' | xargs clang-tidy -p bin
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: bin
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          ls
          pwd
          ls *
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Test
        run: |
          cd bin
          ./SafeCastTest
